services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grupo7
      MYSQL_USER: root
      MYSQL_PASSWORD: A170498b!
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-container
    depends_on:
      - mysql
    volumes:
      - ./panthon_scripts:/app/panthon_scripts
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=A170498b!
      - MYSQL_DB=grupo7
    command: ["python3", "/app/panthon_scripts/main_script.py"]

volumes:
  mysql-data:
